# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=guest
      - MONGO_INITDB_ROOT_PASSWORD=guest
      - MONGO_INITDB_DATABASE=project
    ports:
      - '27018:27017'

volumes:
  mongodb-data:

networks:
  dev:
